### PR TITLE
Made the website Super-Responsive and did some minor changes that are…

### PR DESCRIPTION
**Pull request by 3xp11i**
… recommended in web design

## 🛠️ Fixes Issue
The website was very unresponsive, so I have made some very essential changes. Moreover, I have modified the CSS a little bit to make the website look better. I have also converted some ids to classes which is a good practice in web development, without breaking the functionality of the website. 

## 👨‍💻 Changes proposed
- Added Media queries for responsiveness
- Changed some units for the same purpose
- Added some margin, padding, etc.
- Removed unnecessary heights and widths which are the main culprit for unresponsiveness
- Added some flex properties

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
You can check yourself, I have tested it on my side. 👍

## 📷 Screenshots
image

https://user-images.githubusercontent.com/65062036/184809882-d4f251df-427e-44da-b34b-5dc75e80a3f0.mp4

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,
Thank you for the PR. But the #7 is already opened by someone else and they are already working on that. I am drafting the PR, if due to any reason their PR didn't get merged we will move with this.

Also, don't start directly working on a PR, before getting the issue assigned.

**Comment by 3xp11i** [comment]
Hmm, I am sorry @Pradumnasaraf  I was not knowing about this thing. I will take care from now on. I will be waiting for your decision. Thanks for your time.

**Comment by Pradumnasaraf** [comment]
> Hmm, I am sorry @Pradumnasaraf I was not knowing about this thing. I will take care from now on. I will be waiting for your decision. Thanks for your time.

Thank you, I will soon notify you :)

**Comment by 3xp11i** [comment]
I guess you forgot about this, please check.

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,
I don't want to change the original look of the current side, we just want to make it responsive

Look (after you change)
Screenshot from 2022-08-28 20-51-29

Original look 
Screenshot from 2022-08-28 20-54-05


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Pradumnasaraf** [comment]
No activity, closing this PR

**Pull request closed without merging**
