### PR TITLE
CSS modified for responsiveness

### PR DESCRIPTION
**Pull request by Andyy-18**
## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Hey, It doesn't look much responsive. Please make according to certain. Need to work on the `Max-width` property.

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Thank you for the PR.
Hey, It doesn't look much responsive. Please make according to certain. Need to work on the `Max-width` property.

Also, don't start directly working on a PR, before getting the issue assigned.

**Comment by Andyy-18** [comment]
Ok @Pradumnasaraf bro. I didn't know about it.
Can you tell me please how to get a issue assign ?
I don't know about it.

**Comment by Pradumnasaraf** [comment]
> Ok @Pradumnasaraf bro. I didn't know about it. Can you tell me please how to get a issue assign ? I don't know about it.

You can comment below on any issue and the maintainer will assign you!

**Comment by Andyy-18** [comment]
Ok bro.Thanks.

**Pull request closed without merging**
